import { EventEmitter } from 'events';

export class AppEventBus extends EventEmitter {}

export const eventBus = new AppEventBus();

// Typed event names
export const SystemEvents = {
  WALLET_ADDED: 'WALLET_ADDED',
  WALLET_UPDATED: 'WALLET_UPDATED',
  WALLET_DELETED: 'WALLET_DELETED',
  TRANSACTION_DETECTED: 'TRANSACTION_DETECTED',
  TRADE_DETECTED: 'TRADE_DETECTED',
  POSITION_UPDATED: 'POSITION_UPDATED',
  POSITION_CLOSED: 'POSITION_CLOSED',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  METRICS_UPDATED: 'METRICS_UPDATED',
  CONNECTION_STATUS_CHANGED: 'CONNECTION_STATUS_CHANGED',
  PAPER_TRADE_EXECUTED: 'PAPER_TRADE_EXECUTED',
  PAPER_POSITION_UPDATED: 'PAPER_POSITION_UPDATED',
  TOKEN_RISK_UPDATED: 'TOKEN_RISK_UPDATED',
  BUY_ENTRY_RESOLVED: 'BUY_ENTRY_RESOLVED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
};
